---
name: ad-mqtt
version: dev
slug: ad-mqtt
description: MQTT Bridge for AlarmDecoder
url: https://github.com/dgrnbrg/ad-mqtt
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: application
services:
  - mqtt:need
options:
  system_packages: []
  python_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  init_commands:
    - str
