---
name: ad-mqtt
version: dev
slug: ad-mqtt
description: MQTT Bridge for AlarmDecoder
url: https://github.com/dgrnbrg/ad-mqtt
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: application
services:
  - mqtt:need
options:
  alarm:
    host: null
    port: 10000
    restore_on_startup: True
    code: null
  devices:
    - zone: null
      entity: null
      label: null
      is_virtual: False
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  alarm:
    host: str
    port: int
    restore_on_startup: bool
    code: str
  devices:
    - zone: int
      entity: str
      label: str
      device_class: str?
      is_virtual: bool
